"use client";

import type { BrochureData } from "@/lib/extract-brochure";

type Props = {
  data: BrochureData;
  aiUsed?: boolean;
};

export function BrochurePreview({ data, aiUsed }: Props) {
  return (
    <article
      className="brochure-sheet mx-auto max-w-4xl overflow-hidden rounded-2xl border border-amber-900/15 bg-gradient-to-br from-amber-50 via-white to-orange-50/80 shadow-xl shadow-amber-900/10 print:max-w-none print:rounded-none print:border-0 print:shadow-none"
    >
      <header className="border-b border-amber-900/15 bg-gradient-to-r from-teal-800 via-teal-900 to-emerald-950 px-8 py-10 text-white print:py-8">
        <p className="font-mono text-xs uppercase tracking-[0.2em] text-teal-200/90">
          Site brochure
        </p>
        <h1 className="mt-3 font-serif text-3xl font-semibold tracking-tight md:text-4xl">
          {data.siteName}
        </h1>
        <p className="mt-4 max-w-xl text-base leading-relaxed text-teal-100/95">
          {data.tagline}
        </p>
        {aiUsed ? (
          <p className="mt-3 inline-block rounded-full bg-white/10 px-3 py-1 text-xs text-teal-100">
            Copy refined with AI — verify on the live site
          </p>
        ) : null}
      </header>

      <div className="grid gap-0 md:grid-cols-12">
        <section className="border-b border-amber-900/10 p-8 md:col-span-7 md:border-b-0 md:border-r">
          <h2 className="font-serif text-lg font-semibold text-teal-900">
            Inside story
          </h2>
          <div className="mt-5 space-y-6">
            {data.sections.map((s, i) => (
              <div key={i} className="border-l-2 border-teal-600/40 pl-4">
                <h3 className="font-semibold text-zinc-900">{s.title}</h3>
                <p className="mt-2 whitespace-pre-line text-sm leading-relaxed text-zinc-700">
                  {s.body}
                </p>
              </div>
            ))}
          </div>
        </section>

        <aside className="bg-amber-100/40 p-8 md:col-span-5">
          <h2 className="font-serif text-lg font-semibold text-teal-900">
            Quick facts
          </h2>
          {data.highlights.length > 0 ? (
            <ul className="mt-4 space-y-3">
              {data.highlights.map((h, i) => (
                <li
                  key={i}
                  className="flex gap-2 text-sm leading-snug text-zinc-800"
                >
                  <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-teal-600" />
                  <span>{h}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="mt-4 text-sm text-zinc-600">
              No bullet list found on the page — headings and paragraphs still
              capture the story.
            </p>
          )}
          <div className="mt-8 rounded-xl border border-amber-900/15 bg-white/80 p-4 text-xs text-zinc-600">
            <p className="font-medium text-zinc-800">Source</p>
            <a
              href={data.sourceUrl}
              className="mt-1 block break-all text-teal-800 underline decoration-teal-800/30 underline-offset-2 hover:decoration-teal-800"
              target="_blank"
              rel="noopener noreferrer"
            >
              {data.sourceUrl}
            </a>
          </div>
        </aside>
      </div>

      <footer className="border-t border-amber-900/10 bg-white/60 px-8 py-4 text-center text-xs text-zinc-500">
        Generated by Brochure Studio — for preview and print only
      </footer>
    </article>
  );
}
